services:

  influxdb:
    image: influxdb:1.8
    container_name: bench-influxdb
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    ports:
      - "18086:8086"
    networks:
      bench-lan:
        ipv4_address: 172.19.1.200
    volumes:
      - influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: bench-grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "13000:3000"
    networks:
      bench-lan:
        ipv4_address: 172.19.1.201
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  influxdb-data:
  grafana-data:
